path: C:\Users\guzel\OneDrive\Documents\thesis\thesis_project\data
train: images/train
val: images/val

nc: 6

names:
  0: drinks
  1: healthcare
  2: personal
  3: cleaning
  4: glassware
  5: food

  # {'drinks': 0, 'healthcare': 1, 'personal': 2, 'cleaning': 3, 'glassware': 4, 'food': 5}
