path: C:\Users\guzel\OneDrive\Documents\thesis\thesis_project\data # dataset root dir
train: images # relative to path
val: images # relative to path

names:
  0: water_and_drinks
  1: healthcare
  2: personal_care
  3: home
  4: food
  5: pets
